local t = require("tests.lib")
local Hud = require("src.hud")
local TouchControls = require("src.touch_controls")

local WIDTH, HEIGHT = 1280, 720

local function newControls()
    local hud = Hud.new()
    hud:resize(WIDTH, HEIGHT)
    return TouchControls.new(hud)
end

local function buttonNamed(controls, name)
    for _, button in ipairs(controls.hud.buttons) do
        if button.name == name then return button end
    end
    error("no button " .. name)
end

t.test("touch: no touches means no input", function()
    local controls = newControls()
    local forward, right, up = controls:movement()
    t.eq(forward, 0); t.eq(right, 0); t.eq(up, 0)
    local dx, dy = controls:takeLook()
    t.eq(dx, 0); t.eq(dy, 0)
    t.eq(#controls:takeActions(), 0)
end)

t.test("touch: direction keys move while held", function()
    local controls = newControls()
    local cases = { forward = { 1, 0 }, back = { -1, 0 }, right = { 0, 1 }, left = { 0, -1 } }
    for name, expected in pairs(cases) do
        local key = buttonNamed(controls, name)
        controls:pressed(name, key.x, key.y)
        local forward, right = controls:movement()
        t.eq(forward, expected[1], name .. " forward"); t.eq(right, expected[2], name .. " right")
        controls:released(name)
    end
    local forward, right = controls:movement()
    t.eq(forward, 0, "released"); t.eq(right, 0)
end)

t.test("touch: sliding across the keys switches direction", function()
    local controls = newControls()
    local forwardKey, rightKey = buttonNamed(controls, "forward"), buttonNamed(controls, "right")
    controls:pressed(1, forwardKey.x, forwardKey.y)
    controls:moved(1, rightKey.x, rightKey.y, rightKey.x - forwardKey.x, rightKey.y - forwardKey.y)
    local forward, right = controls:movement()
    t.eq(forward, 0); t.eq(right, 1)
    controls:moved(1, controls.hud.width / 2, rightKey.y, controls.hud.width / 2 - rightKey.x, 0)
    forward, right = controls:movement()
    t.eq(forward, 0, "off the keys: nothing held"); t.eq(right, 0)
    t.eq(controls:takeLook(), 0, "and it does not look")
end)

t.test("touch: the center of the keys is not a key", function()
    local controls = newControls()
    local forwardKey, backKey = buttonNamed(controls, "forward"), buttonNamed(controls, "back")
    local centerY = (forwardKey.y + backKey.y) / 2
    t.eq(controls.hud:hitTest(forwardKey.x, centerY), nil)
end)

t.test("touch: a touch off the buttons drags the view in units of the shorter side", function()
    local controls = newControls()
    controls:pressed("b", 900, 200)
    controls:moved("b", 972, 200, 72, 0)
    controls:moved("b", 972, 236, 0, 36)
    local dx, dy = controls:takeLook()
    t.near(dx, 0.1); t.near(dy, 0.05)
    dx, dy = controls:takeLook()
    t.eq(dx, 0, "reset after take"); t.eq(dy, 0)
    local forward = controls:movement()
    t.eq(forward, 0, "looking does not move")
end)

t.test("touch: tapping break/place queues actions in order", function()
    local controls = newControls()
    local breakButton, placeButton = buttonNamed(controls, "break"), buttonNamed(controls, "place")
    controls:pressed(1, breakButton.x, breakButton.y)
    controls:released(1)
    controls:pressed(2, placeButton.x, placeButton.y)
    local actions = controls:takeActions()
    t.eq(#actions, 2); t.eq(actions[1], "break"); t.eq(actions[2], "place")
    t.eq(#controls:takeActions(), 0, "cleared after take")
end)

t.test("touch: up/down fly only while held", function()
    local controls = newControls()
    local upButton, downButton = buttonNamed(controls, "up"), buttonNamed(controls, "down")
    controls:pressed(1, upButton.x, upButton.y)
    local _, _, up = controls:movement()
    t.eq(up, 1)
    controls:pressed(2, downButton.x, downButton.y)
    _, _, up = controls:movement()
    t.eq(up, 0, "both held cancel out")
    controls:released(1)
    _, _, up = controls:movement()
    t.eq(up, -1)
    controls:released(2)
    _, _, up = controls:movement()
    t.eq(up, 0)
    t.eq(#controls:takeActions(), 0, "fly buttons are not actions")
end)

t.test("touch: dragging from a button does not look", function()
    local controls = newControls()
    local button = buttonNamed(controls, "place")
    controls:pressed(1, button.x, button.y)
    controls:moved(1, button.x - 50, button.y, -50, 0)
    local dx = controls:takeLook()
    t.eq(dx, 0)
end)

t.test("touch: moving and looking work at the same time", function()
    local controls = newControls()
    local key = buttonNamed(controls, "forward")
    controls:pressed("move", key.x, key.y)
    controls:pressed("look", 1000, 200)
    controls:moved("look", 1036, 200, 36, 0)
    local forward = controls:movement()
    local dx = controls:takeLook()
    t.eq(forward, 1); t.near(dx, 0.05)
end)


t.test("touch: moves and releases of unknown touches are ignored", function()
    local controls = newControls()
    controls:moved("ghost", 10, 10, 5, 5)
    controls:released("ghost")
    local dx = controls:takeLook()
    t.eq(dx, 0)
end)
