local t = require("tests.lib")
local Extent3 = require("src.math.extent3")
local Vec3 = require("src.math.vec3")

t.test("extent3: volume and equality", function()
    local size = Extent3.new(2, 3, 4)
    t.eq(size:volume(), 24)
    t.eq(size, Extent3.new(2, 3, 4))
    t.ok(size ~= Extent3.new(2, 3, 5))
    t.eq(tostring(size), "2x3x4")
end)

t.test("extent3: contains covers 0..size-1 on each axis", function()
    local size = Extent3.new(2, 3, 4)
    t.ok(size:contains(Vec3.new(0, 0, 0)))
    t.ok(size:contains(Vec3.new(1, 2, 3)))
    t.ok(not size:contains(Vec3.new(2, 0, 0)))
    t.ok(not size:contains(Vec3.new(0, 3, 0)))
    t.ok(not size:contains(Vec3.new(0, 0, 4)))
    t.ok(not size:contains(Vec3.new(-1, 0, 0)))
end)

t.test("extent3: index is X-fastest and cell inverts it", function()
    local size = Extent3.new(2, 3, 4)
    t.eq(size:index(Vec3.new(0, 0, 0)), 0)
    t.eq(size:index(Vec3.new(1, 0, 0)), 1)
    t.eq(size:index(Vec3.new(0, 1, 0)), 2)
    t.eq(size:index(Vec3.new(0, 0, 1)), 6)
    for index = 0, size:volume() - 1 do
        local cell = size:cell(index)
        t.ok(size:contains(cell), "cell " .. index .. " inside")
        t.eq(size:index(cell), index)
    end
end)

t.test("extent3: divideRoundingUp covers partial cells", function()
    t.eq(Extent3.new(32, 33, 16):divideRoundingUp(16), Extent3.new(2, 3, 1))
end)
