local t = require("tests.lib")
local Vec3 = require("src.math.vec3")

t.test("vec3: arithmetic operators return new vectors", function()
    local a, b = Vec3.new(1, 2, 3), Vec3.new(4, 5, 6)
    t.eq(a + b, Vec3.new(5, 7, 9))
    t.eq(b - a, Vec3.new(3, 3, 3))
    t.eq(a * 2, Vec3.new(2, 4, 6))
    t.eq(-a, Vec3.new(-1, -2, -3))
    t.eq(a, Vec3.new(1, 2, 3), "operands unchanged")
end)

t.test("vec3: equality compares components", function()
    t.ok(Vec3.new(1, 2, 3) == Vec3.new(1, 2, 3))
    t.ok(Vec3.new(1, 2, 3) ~= Vec3.new(1, 2, 4))
end)

t.test("vec3: dot, cross and length", function()
    local x, y = Vec3.new(1, 0, 0), Vec3.new(0, 1, 0)
    t.eq(x:dot(y), 0)
    t.eq(Vec3.new(1, 2, 3):dot(Vec3.new(4, 5, 6)), 32)
    t.eq(x:cross(y), Vec3.new(0, 0, 1), "right-handed")
    t.eq(Vec3.new(3, 4, 0):length(), 5)
end)

t.test("vec3: normalized keeps direction at unit length", function()
    local n = Vec3.new(0, 3, 4):normalized()
    t.near(n:length(), 1)
    t.near(n.y, 0.6); t.near(n.z, 0.8)
end)

t.test("vec3: floor rounds toward negative infinity", function()
    t.eq(Vec3.new(1.7, -0.2, 3):floor(), Vec3.new(1, -1, 3))
end)

t.test("vec3: tostring", function()
    t.eq(tostring(Vec3.new(1, -2.5, 0)), "(1, -2.5, 0)")
end)

t.test("vec3: division by a number", function()
    t.eq(Vec3.new(2, -4, 6) / 2, Vec3.new(1, -2, 3))
end)

t.test("vec3: per-axis helpers", function()
    t.eq(Vec3.unit("x"), Vec3.new(1, 0, 0))
    t.eq(Vec3.unit("z"), Vec3.new(0, 0, 1))
    local v = Vec3.new(4, 5, 6)
    t.eq(Vec3.fromAxes(function(axis) return v[axis] * 10 end), Vec3.new(40, 50, 60))
    t.eq(Vec3.ZERO, Vec3.new(0, 0, 0))
end)

t.test("vec3: smallestAxis prefers the later axis on ties", function()
    t.eq(Vec3.new(1, 2, 3):smallestAxis(), "x")
    t.eq(Vec3.new(3, 1, 2):smallestAxis(), "y")
    t.eq(Vec3.new(1, 1, 2):smallestAxis(), "y")
    t.eq(Vec3.new(1, 2, 1):smallestAxis(), "z")
    t.eq(Vec3.new(1, 1, 1):smallestAxis(), "z")
    t.eq(Vec3.new(math.huge, 2, math.huge):smallestAxis(), "y")
end)
